apiVersion: v1
kind: Secret
metadata:
  name: mdanielson-ecsopenshift-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJiV1JoYm1sbGJITnZiaXRsWTNOdmNHVnVjMmhwWm5RNlIxbzBNREpJU1ZaTE1UWklTMUJLTjFVMU1rUktSekpHUmtsQlVqVTFXa05PU3paRU5FODJNMDAyVEU1TlZUTlVSREZRVUV0SVdVbElXa28zTUVKQk1RPT0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson