kind: Secret
apiVersion: v1
metadata:
  name: lti-secret
  namespace: jupyterhub
  selfLink: /api/v1/namespaces/jupyterhub/secrets/lti-secret
  uid: 25e38a58-6205-4080-b496-7d401b577309
  resourceVersion: '6412186'
  creationTimestamp: '2020-06-02T10:24:39Z'
data:
  lti_client_secret: >-
    ZDRlZGJjYzBiNmY4NTZmYTZjMWMzNzRhNjliNWM0ZjgzMDQ1NDEyMGJkNTI2YWQxZWQ1ZTQzYjQwZTYzOWY0Nw==
type: Opaque